set guifont=Meslo\ LG\ S\ for\ Powerline\ 10

"window size
set lines=50
set columns=90

"menus
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

"show console dialogs
set guioptions+=c

"remove balloon
set noballooneval
let g:netrw_nobeval = 1

"silent bell
autocmd GUIEnter * set vb t_vb=
