# sourced in interactive shell

if [ -d $HOME/.zsh ]; then
  for file in $HOME/.zsh/**/*.zsh; do
    source $file
  done
fi

export WK="$HOME/Workspace"
export AAKU="$WK/aaku"
export PATH="$PATH:$AAKU/bin"
export PATH="$PATH:$WK/bin"

# chruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Go
export GOPATH="$WK/go"
export PATH="$PATH:$GOPATH/bin"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
