# sourced in interactive shell

include () {
  [[ -f "$1" ]] && source "$1"
}

if [ -d $HOME/.zsh ]; then
  for file in $HOME/.zsh/**/*.zsh; do
    source $file
  done
fi

export WK="$HOME/Workspace"
export AAKU="$WK/aaku-server"
export PATH="$PATH:$AAKU/bin"
export PATH="$PATH:$WK/bin"

# chruby
include /usr/local/share/chruby/chruby.sh
include /usr/local/share/chruby/auto.sh

# Go
export GOPATH="$WK/go"
export PATH="$PATH:$GOPATH/bin"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --color never'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# k8s
source <(kubectl completion zsh)
